config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments
  end
  resources :projects
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum:5, maximum:50}
  validates :body, presence: true, length: {minimum:10, maximum:500}
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum role: [:user, :moderator, :admin]
  after_initialize :set_defaulet_role, :if => :new_record?
  def set_defaulet_role
    self.role ||= :user
  end
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post
  
    def create
      @comment = @post.comments.create(comment_params)
      @comment.user = current_user
  
      if @comment.save
        redirect_to post_path(@post), notice: 'Comment has been created'
      else
        redirect_to post_path(@post), alert: 'Comment has not been created'
      end
    end
  
    def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
    end
  
    def update
      @comment = @post.comments.find(params[:id])
  
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to post_url(@post), notice: 'Comment has been updated' }
        else
          format.html { redirect_to post_url(@post), alert: 'Comment was not updated!' }
        end
      end
    end
  
    private
  
    def set_post
      @post = Post.find(params[:post_id])
    end
  
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
    @projects = Project.all
   @project = Project.new

  end

 # GET /projects/new
 def new
   @project = Project.new
 end

 # GET /projects/1/edit
 def edit
 end

 # POST /projects or /projects.json
 def create
   @project = Project.new(project_params)

   respond_to do |format|
     if @project.save
       format.html { redirect_to root_path, notice: "Project was successfully created." }
       format.json { render :show, status: :created, location: @project }
     else
       format.html { render :new, status: :unprocessable_entity }
       format.json { render json: @project.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /projects/1 or /projects/1.json
 def update
   respond_to do |format|
     if @project.update(project_params)
       format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
       format.json { render :show, status: :ok, location: @project }
     else
       format.html { render :edit, status: :unprocessable_entity }
       format.json { render json: @project.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /projects/1 or /projects/1.json
 def destroy
   @project.destroy

   respond_to do |format|
     format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_project
     @project = Project.find(params[:id])
   end

   # Only allow a list of trusted parameters through.
   def project_params
     params.require(:project).permit(:name, :description, :user_id)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, excert: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    if @project.user != current_user
      redirect_to root_path
    end
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<%= stylesheet_link_tag "style" %>

<div class="container3322">

<div class="comment-<%= comment.id %> container">
<h2><%= comment.user.email %></h2>    
<% if (comment.updated_at - comment.created_at) > 1 %>
<h5>Edited <%= time_ago_in_words(comment.updated_at) %> ago</h5>
<% else %>
<h5>Posted <%= time_ago_in_words(comment.created_at) %> ago</h5>
<% end %>
<% if current_user == comment.user %>
<div class="btn-group float-end">
  <%= link_to "Edit", nil, remote: true, class:"btn btn-warning mx-2",
  data: {
    controller: "comments", action: "comments#toggleForm", comments_form_param: "edit-form-#{comment.id}", comments_body_param: "comment-body-#{comment.id}",
  } %>
  <%= button_to "Delete", [post, comment], class:"btn btn-danger", method: :delete %>
</div>

  <div id="edit-form-<%= comment.id%>" class="d-none">
    <%= render 'comments/form', post: @post, comment: comment, submit_label: "Update" %>
  </div>

<% end %>
<hr />
<div id="comment-body-<%= comment.id %>">
<h1><%= comment.body %></h1>
</div>
</div>

</div>

app/views/comments/_form.html.erb
<%= stylesheet_link_tag "style" %>

<div class="commits">

<%= form_with(model: [post, comment]) do |f| %>
  <div class="form-control">
    <%= f.rich_text_area :body %>
    <%= f.submit submit_label, class: "btn btn-primary mt-1" %>
  </div>
<% end %>


</div>

app/views/layouts/_alert.html.erb
<%if notice%>
    <p class="notice"><%= notise %><p>
<% elsif alert%>
    <p class="alert"><%= alert %><p>
<% end %>

app/views/layouts/_navbar.html.erb
<%- if controller_name == 'pages' %>
<body class="navber-body">

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
   <%- if controller_name == 'pages' %>
        <%= link_to "New posts", posts_path, class:"btn btn-primary mx-2" %>      
        <% end %>
        

        <%- if controller_name == 'pages' %>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-right: 10px;">New Project</button>
        <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
       <ul class="navbar-nav">
        <%- if controller_name == 'pages' %>
              <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
              <li><a class="nav-link scrollto active" href="#about">About</a></li>
              <li><a class="nav-link scrollto active" href="#portfolio">Portfolio</a></li>
              <li><a class="nav-link scrollto active" href="#team">Team</a></li>
              <div class="act"></div>
        <% end %>

        

        
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= current_user.email %>
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit Account", edit_user_registration_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>


</body>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' if current_user %>
    <div class="container" style="margin-top: 15px;">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_new.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= stylesheet_link_tag "glavniy" %>

<body class="body-1">



  <div class="container">
    <% if current_user %>
  
  <h1 class="h1-project">My Basecamp Projects</h1><br/><br/>
          <div class="row">
      <% @projects.each do |project| %>
          <% if current_user.id == project.user.id %>


  <div class="card" style="width: 18rem; margin-left: 0.5rem;  margin-top: 0.5rem;">
    <div class="card-body">
      <h5 class="card-title"><%= project.name %></h5>
      <p class="card-text"><%= project.description %></p>
      <%= link_to "Show", project, class:"card-link btn btn-primary" %>
    </div>
  </div>
  <% end %>
  <% end %>
  </div>
  </div>
  <%= render 'projects/form' %>

  <% else %>
  <h1 class="h1">My Basecamp</h1>
  
      
      <div class="button">
        <%= link_to "Sign Up!", new_user_registration_path , class:"btn" %>

        <%= link_to "Login", new_user_session_path , class:"btn"%>
      </div>
  <% end %>

  </div>

  


</body>

app/views/posts/_form.html.erb
<%= stylesheet_link_tag "style" %> 

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block", class: "sozlar2" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :body, style: "display: block", class: "sozlar2" %>
    <%= form.text_area :body,class: "form-control", cols: "50" %>
  </div>
  <div>
    <%= form.label :body, style: "display: block", class: "sozlar2" %>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="gradient" id="<%= dom_id post %>">

    <h2><%= post.title %></h2>
    <h4>posted by <%= post.user.email %></h4>
    <h6><%= pluralize(post.views, "views") %></h6>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="ends">
  <%= link_to "Show this post", @post, class: "btn btn-primary mx-2" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-danger" %>
</div>



<body class="body-qismi">

    <h1 class="h1-4">Editing post</h1>

    <div class="ortaga1">
    
        
      <div class="ortaga">
        <%= render "form", post: @post %>

        <br>

        <div class="btn-88">
          <%= link_to "Back to posts", posts_path, class: "btn btn-warning" %>
        </div>
      </div>

    </div>

</body>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "style" %>

<body class="body-qismi">

<div class="container">


<div class="nav-2">
  <%= link_to "New post", new_post_path, class: "btn mx-2"%>
  <%= link_to "Back", root_path, class: "btn" %>
</div>

<div class="malumot">

    
<h1 class="h1-1">New Posts</h1>

<div class="col1">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post, class: "btn" %>
    </p><hr />  <br /> 
  <% end %>
</div>

</div>





</div>

</body>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "style" %>  

<body class="body-qismi">

    <h1 class="h1-4">New post</h1>

    <div class="ortaga1">
    
        
      <div class="ortaga">
        <%= render "form", post: @post %>

        <br>

        <div class="btn-88">
          <%= link_to "Back to posts", posts_path, class: "btn btn-warning" %>
        </div>
      </div>

    </div>

</body>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "style" %>

<body class="body-qismi">

  <div class="editslar">
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-warning mx-2" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-danger mx-2" %>
  <%= button_to "Delete this post", @post, method: :delete, class: "btn btn-primary mx-2" %>
  </div>

  <div class="container14">   
  <%= render @post %>

  </div>
  <div class="container443">
  <%= render 'comments/form', 
  post: @post, 
  comment: @post.comments.build,
  submit_label: "Reply" %>

    
      <% @comments.each do |comment| %>
        <div class="contentlaruchun">
      <%= render 'comments/comment', 
      post: @post, 
      comment: comment %>
      </div>
      <% end %>
    

  </div>


</body>

app/views/projects/_form.html.erb
<%= form_with(model: @project) do |form| %>
  <% if @project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize( @project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Name:</label>
            <%= form.text_field :name, class:"form-control" %>
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description:</label>
                <%= form.text_area :description, class:"form-control" %>
                  <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>

          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit class:"btn btn-dark" %>

      </div>
    </div>
  </div>
</div>
  <div>
  </div>


<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1 class="h1-project">Projects</h1>

<%= stylesheet_link_tag "register" %>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>
<%= link_to "sign out", new_user_session_path %>

app/views/projects/new.html.erb
<h1>New project</h1>


<%= render "form", project: @project %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>


<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<body class="field22">
    <%= stylesheet_link_tag "style" %>
<%= render 'form' %>


  

  <div class="row-21">
    <h3>Basecamp</h3>
    
  </div>

  <div class="collapsers">

  <div class="row-22">
    <div>
      <%= link_to "Back", new_user_session_path, class: "btn btn-primary" %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-right: 10px;">Edit Project</button>
    </div>
    <%= button_to "Delete Project", @project, method: :delete, style: "float: right;", class: "btn btn-danger" %>
  </div>


    <h1 style="text-align:center; font-size: 120px; color: rgb(53, 209, 236);" class="mt-5"><%= @project.name %></h1>

  </div>

</body>